import matplotlib.pyplot as plt
import os

# Get the folder where graph.py is located
folder = os.path.dirname(os.path.abspath(__file__))

# Locate data.txt in the same folder
data_file = os.path.join(folder, "data.txt")

elements = []
binary = []
ternary = []

# Read data generated by the C program
with open(data_file, "r") as file:

    # Skip header
    next(file)

    for line in file:
        values = line.split()

        elements.append(int(values[0]))
        binary.append(int(values[1]))
        ternary.append(int(values[2]))

# Generate graph
plt.plot(elements, binary, marker='o', label="Binary Search")
plt.plot(elements, ternary, marker='o', label="Ternary Search")

plt.xlabel("Number of Elements (n)")
plt.ylabel("Number of Comparisons")
plt.title("Binary Search vs Ternary Search")

plt.legend()
plt.grid(True)
plt.tight_layout()

# Save graph in the same folder
graph_file = os.path.join(folder, "binary_vs_ternary.png")
plt.savefig(graph_file)

# Display graph
plt.show()