import pandas as pd
import matplotlib.pyplot as plt

# Read CSV generated by C program
data = pd.read_csv("strassen_data.csv")

print("\nStrassen Matrix Multiplication Data")
print("-----------------------------------")
print(data)

# Create graph
plt.figure(figsize=(10, 6))

plt.plot(
    data["n"],
    data["strassen_multiplications"],
    marker="o",
    label="Strassen Multiplications"
)

plt.plot(
    data["n"],
    data["theoretical_multiplications"],
    marker="s",
    linestyle="--",
    label=r"Theoretical $n^{log_2 7}$"
)

plt.xlabel("Matrix Size (n × n)")
plt.ylabel("Number of Scalar Multiplications")

plt.title("Strassen Matrix Multiplication - Divide and Conquer")

plt.legend()
plt.grid(True)

plt.tight_layout()

# Save graph
plt.savefig("strassen_graph.png", dpi=300)

# Display graph
plt.show()