import pandas as pd
import matplotlib.pyplot as plt

# Read data generated by C program
data = pd.read_csv("max_min_data.csv")

# Display data
print("\nExperimental Data")
print("-----------------")
print(data)

# Create graph
plt.figure(figsize=(10, 6))

plt.plot(
    data["n"],
    data["comparisons"],
    marker="o",
    label="Actual Comparisons"
)

plt.plot(
    data["n"],
    data["theoretical_bound"],
    marker="s",
    linestyle="--",
    label="Theoretical Bound (3n/2)"
)

plt.xlabel("Input Size (n)")
plt.ylabel("Number of Comparisons")

plt.title("Max-Min using Divide and Conquer")

plt.legend()
plt.grid(True)

plt.tight_layout()

# Save graph
plt.savefig("max_min_graph.png", dpi=300)

# Display graph
plt.show()