import matplotlib.pyplot as plt

coins = []
comparisons = []

# Read data generated by the C program
with open("data.txt", "r") as file:

    # Skip the header
    next(file)

    for line in file:
        values = line.split()

        coins.append(int(values[0]))
        comparisons.append(int(values[1]))

# Generate graph
plt.plot(coins, comparisons, marker='o')

plt.xlabel("Number of Coins (n)")
plt.ylabel("Number of Comparisons")

plt.title("Defective Coin Search - Time Complexity")

plt.grid(True)

plt.tight_layout()

# Save graph
plt.savefig("defective_coin_graph.png")

# Display graph
plt.show()