import pandas as pd
import matplotlib.pyplot as plt

# Read data generated by C
data = pd.read_csv("selection_sort_data.csv")

print("\nSelection Sort Experimental Data")
print("---------------------------------")
print(data)


# Create graph
plt.figure(figsize=(10, 6))


# Best case
plt.plot(
    data["n"],
    data["best_case"],
    marker="o",
    label="Best Case"
)


# Worst case
plt.plot(
    data["n"],
    data["worst_case"],
    marker="s",
    label="Worst Case"
)


# Average case
plt.plot(
    data["n"],
    data["average_case"],
    marker="^",
    label="Average Case"
)


# Theoretical
plt.plot(
    data["n"],
    data["theoretical"],
    linestyle="--",
    label=r"Theoretical $n(n-1)/2$"
)


plt.xlabel("Input Size (n)")
plt.ylabel("Number of Comparisons")

plt.title(
    "Selection Sort - Experimental Validation"
)

plt.legend()

plt.grid(True)

plt.tight_layout()


# Save graph
plt.savefig(
    "selection_sort_graph.png",
    dpi=300
)


# Display graph
plt.show()